Feature/plmc 267 add complexity parameters to extrinsic benchmarks
Polimec/polimec-node pull request #148
Opened 2024-01-17 16:51 UTC by JuaniRios

## What?
Add complexity parameters to the existing extrinsic benchmarks, as well as split them into different benchmarks for each logic path

## Why?
Get a more accurate weight to avoid the chain stalling, and avoid overcharging our users.

## How?
For the complexity parameters, I checked which storage items were being used, and if the amount of reads/writes depended on any 
inputs or previous conditions. For example if an extrinsic needed to get all contributions made by a user, then it meant it had to do
one storage read per existing contribution by that user. So a complexity parameter in this case would be the amount of existing 
contributions for that user before calling the benchmark.

For the logic paths I looked at any if statements.

## Testing?
- Run benchmark tests by calling `cargo test --features runtime-benchmarks bench_`
- Run real benchmarks to see the weight differences by calling `cargo run --features runtime-benchmarks,fast-gov -p polimec-parachain-node -- benchmark pallet --chain=polimec-rococo-local --steps=50 --repeat=20 --pallet=pallet_funding --extrinsic="*" --output="dbg-weights.rs"`
  (WARNING: it will take a long time)

## Screenshots (optional)

## Anything Else?
- We are still missing the benchmarks for the hrmp extrinsics. But next I will focus on the do_ functions which are called in other places except extrinsics (like on_initialize).

2024-02-08 12:37 UTC, lrazovic requested changes
> The second most difficult thing after writing FRAME benchmarks correctly is to review them. 
> 
> Confucius, 499 BCE

From my analysis and the construction of the worst-case scenarios, it appears we have achieved the goal. The comments received are primarily stylistic, without affecting the benchmarks' overall logic. A review of the guidelines at [Polkadot Blockchain Academy](https://polkadot-blockchain-academy.github.io/pba-book/frame/benchmarking-1/page.html) (and Benchmarking-2) confirms that we are in compliance with all the recommendations.

GG!

2024-02-08 12:40 UTC, lrazovic commented on pallets/funding/src/functions.rs
> +		let actual_weight = if existing_evaluations_count == 0 {
```suggestion
  let actual_weight = if existing_evaluations_count.is_zero()
```

2024-02-08 12:46 UTC, JuaniRios commented on pallets/funding/src/functions.rs
> +		// benchmark variables
Comment is misleading, should be "weight calculation variables". We use them to return to the user the correct weight used, so they are needed always

2024-02-08 12:47 UTC, JuaniRios commented on pallets/funding/src/functions.rs
> +		enum WeightContributionFlag {
Should we?
It's not used anywhere else, and the enum is just an easier way of representing the data than a long variable name with comments.
I vote keep it in, unless there is some sort of convention I'm not aware of

2024-02-08 15:19 UTC, JuaniRios commented on pallets/funding/src/lib.rs
> +		type MaxProjectsToUpdateInsertionAttempts: Get<u32>;
e40634f4

2024-02-08 15:21 UTC, JuaniRios commented on pallets/funding/src/lib.rs
> +		#[pallet::weight(WeightInfoOf::<T>::start_auction_manually(<T as Config>::MaxProjectsToUpdateInsertionAttempts::get() - 1, 10_000u32))]
Its already explained in line 1041. Should we explain the same parameter every time it's used?

2024-02-08 15:23 UTC, JuaniRios commented on pallets/funding/src/functions.rs
> +		// benchmark variables
837e19c6247f17ca048c088f738368b4a15b8d08

2024-02-08 16:17 UTC, JuaniRios commented on pallets/funding/src/functions.rs
done

2024-02-08 16:17 UTC, JuaniRios commented on pallets/funding/src/benchmarking.rs
done

2024-02-09 13:36 UTC, vstam1 approved these changes
As far as I understand, the logic looks good.

2024-02-09 14:49 UTC, lrazovic approved these changes

2024-02-09 15:24 UTC, merged