Feature/split contributions
Polimec/polimec-node pull request #176
Opened 2024-02-23 13:00 UTC by vstam1

## What?
- Split extrinsics into community and remainder contributions
- Simplify contribute benchmarks and weight returns
- call inner do_functions in tests

## Why?
- In the community, we need to check if the user has a winning bid already, and if so return err. The credential check should be the same though.
  - The token amount left to buy is different in each round
- Was too complex, making it harder to maintain. It's now less accurate but its a worthy tradeoff
- Extrinsic calls will do credential checks, and we don't want those in pallet tests. We do those in integration tests 

## How?
- abstract common logic into private function, create 2 public functions with a distinct logic
- assume we always create the ct account, and we always do some sort of iteration over users. We now have only 2 logic paths, either the contribution ends the round or it doesn't. The rest of the logic branches get included in the linear interpolation (even though it's not a linear relationship)

## Testing?
- Since we made the original do_contribute private, we are now forced to replace all calls with either community or remainder contribute calls. So just run `cargo test`
- Run benchmark tests and benchmark weight generation and check results.
- Add a test for the winning bidder to not be accepted in the community but in the remainder.

## Anything Else?
Next PR should make the default values used in tests to be more complex, to be in line with the new logic of who gets to participate in the community.

2024-02-27 09:30 UTC, JuaniRios approved these changes
I coded the last part of the PR so LGTM

2024-02-28 09:15 UTC, lrazovic requested changes

2024-02-28 09:15 UTC, lrazovic commented on integration-tests/src/tests/basic_comms.rs
What's the reasoning behind these changes?

2024-02-28 09:15 UTC, lrazovic commented on integration-tests/src/tests/mod.rs
> +// infinite loop
```suggestion
```

2024-02-28 09:15 UTC, lrazovic commented on pallets/funding/src/weights_old.rs
Can we remove this file?

2024-02-28 09:15 UTC, lrazovic commented on rust-toolchain.toml
> +channel = "nightly-2023-12-01"
```suggestion
channel = "1.74.0"
```

2024-02-28 09:56 UTC, JuaniRios commented on integration-tests/src/tests/basic_comms.rs
oops, forgot to uncomment

2024-02-28 09:57 UTC, JuaniRios commented on pallets/funding/src/weights_old.rs
yes

2024-02-28 10:09 UTC, lrazovic approved these changes
One last very minor comment, but great simplification!

2024-02-28 10:09 UTC, lrazovic commented on integration-tests/src/tests/basic_comms.rs
> +
Is this needed?

2024-02-28 10:11 UTC, JuaniRios commented on integration-tests/src/tests/basic_comms.rs
> +
good catch!

2024-02-28 10:11 UTC, merged