chore: first batch of weights
Polimec/polimec-node pull request #228
Opened 2024-04-11 09:33 UTC by lrazovic

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-04-12 07:49 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
> +	type WeightInfo = ();
We need to adjust the benchmarks. This will be addressed in an upcoming PR.

2024-04-12 08:40 UTC, vstam1 approved these changes
Lgtm. Small question (is a my mistake). Currently all the settlement extrinsics do not have the correct weight set (just a Weight of 0). Could you use the correct weight benchmarking there in this PR?

2024-04-12 13:25 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
> +	type WeightInfo = ();
Fixed here https://github.com/Polimec/polimec-node/pull/231

2024-04-15 13:49 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
> +	type WeightInfo = ();
Fixed in https://github.com/Polimec/polimec-node/pull/235.

2024-04-15 13:50 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
> +	type WeightInfo = ();
Fixed in https://github.com/Polimec/polimec-node/pull/233.

2024-04-15 13:56 UTC, JuaniRios requested changes
Can you add screenshots with the weight diffs of each changed weight file?
You can fix your previous issue by renaming both files you want to compare to the same name.
Would save time for me and Just if one person does that once

2024-04-15 15:54 UTC, lrazovic commented
> Can you add screenshots with the weight diffs of each changed weight file? You can fix your previous issue by renaming both files you want to compare to the same name. Would save time for me and Just if one person does that once

Sure. [Here](https://gist.github.com/lrazovic/170b2d112b7343a0adda2ad31ba033e2) you can find a list showcasing the main differences between the weights we were using before, and the new ones. The comparison is not exactly optimal because `subweight` sometimes has problems comparing weights generated with different runtimes, as in this case, but the next time we have to generate weights, the comparison will be more reliable.

2024-04-15 16:04 UTC, lrazovic commented
We realized that the `WeightInfo` for `pallet_xcm` are missing, the benchmarks needs a fix :( @vstam1 

```
Error: Input("Benchmark pallet_xcm::send failed: SendFailure")
2024-04-15 18:03:00 Starting benchmark: pallet_xcm::send
```

Command to reproduce: `cargo run --features runtime-benchmarks --release benchmark pallet --chain=polimec-local --pallet="pallet_xcm" --extrinsic="*"`

2024-04-16 15:56 UTC, lrazovic commented
> We realized that the `WeightInfo` for `pallet_xcm` are missing, the benchmarks needs a fix :( @vstam1
> 
> ```
> Error: Input("Benchmark pallet_xcm::send failed: SendFailure")
> 2024-04-15 18:03:00 Starting benchmark: pallet_xcm::send
> ```
> 
> Command to reproduce: `cargo run --features runtime-benchmarks --release benchmark pallet --chain=polimec-local --pallet="pallet_xcm" --extrinsic="*"`

Fixed in https://github.com/Polimec/polimec-node/pull/239.

2024-04-17 09:42 UTC, JuaniRios commented
![CleanShot 2024-04-17 at 11 41 46](https://github.com/Polimec/polimec-node/assets/54085674/f2858457-82e6-4d38-a3cc-8bfc9ee47be2)
`just dry-run-benchmarks` is failing on pallet-funding

2024-04-17 09:55 UTC, JuaniRios approved these changes
Seems the heaviest changes are between 20 and 80%. It's hard to tell if it's too much since we are comparing pallet weights with a real runtime weights.

Let's merge for now, and keep in mind the next weight diffs should be <20% (Joe's feedback)

2024-04-17 09:55 UTC, merged