Paseo config
Polimec/polimec-node pull request #317
Opened 2024-06-05 13:15 UTC by JuaniRios

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-06-18 08:43 UTC, vstam1 reviewed
Think in general it looks pretty good! Couple of comments. Do think its good if Leo has some time to take a second look, as I'm no node side expert, so might not have seen some things.

2024-06-18 08:43 UTC, vstam1 commented on nodes/parachain/src/chain_spec/common.rs
> +use itertools::Itertools;
Why do we need the Itertools again?

2024-06-18 08:43 UTC, vstam1 commented on scripts/zombienet/polimec-polkadot-assethub-penpal.toml
> +    [[parachains.collators]]g
Sure this works? There is some random 'g' here at the end

2024-06-18 08:43 UTC, vstam1 commented on scripts/zombienet/polimec-polkadot-assethub-penpal.toml
> +    args = ["--offchain-worker when-authority", "-lerror", "-lxcm::process_instruction=trace", "-lxcm::execute_xcm_in_credit=trace", "-lxcm::barriers=trace", "-lpallet_funding::hrmp=trace", "-lpallet
Maybe only use the args for 1 collator? We will probably only check the logs with a single collator. Let me know if you think otherwise

2024-06-19 13:24 UTC, JuaniRios commented on nodes/parachain/src/chain_spec/common.rs
> +use itertools::Itertools;
`collect_vec`

2024-06-21 07:28 UTC, vstam1 approved these changes
Lgtm, but Leo should definitely do a review as well!

2024-06-21 07:46 UTC, lrazovic requested changes
We are ready to take the leap to Paseo!

Adding the raw chainspec to the node would be a huge help when it comes to setting up collators

2024-06-21 07:46 UTC, lrazovic commented on nodes/parachain/Cargo.toml
> +itertools = "0.10.5"
Let's use the workspace https://github.com/Polimec/polimec-node/blob/205b7c41dd7c7f5ba9927694397e49d5bcf10f91/Cargo.toml#L88

2024-06-21 07:46 UTC, lrazovic commented on nodes/parachain/src/command.rs
> +		"polimec" => Box::new(chain_spec::common::ChainSpec::from_json_bytes(polimec_chain_spec)?),
Can we please add the raw chainspec in the node so we can start a collator by using something like `--chain polimec-paseo`?

2024-06-21 15:49 UTC, lrazovic approved these changes

2024-06-21 16:02 UTC, merged