simplifications part 3
Polimec/polimec-node pull request #363
Opened 2024-07-22 12:15 UTC by JuaniRios

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-07-22 12:15 UTC, JuaniRios commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/363?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#363** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/363?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#362** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/362?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#361** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/361?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#358** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-02 11:54 UTC, vstam1 requested changes

2024-08-02 11:54 UTC, vstam1 commented on pallets/funding/src/functions/misc.rs
>  			project_details.fundraising_target_usd,
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +257]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->Here we still have the Y calculation for rewards info. Should be removed as well. <!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/363?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-08-06 08:06 UTC, lrazovic approved these changes

2024-08-09 10:16 UTC, vstam1 approved these changes

2024-08-23 09:56 UTC, JuaniRios commented
### Merge activity

* **Aug 23, 5:56 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/363).

2024-08-23 10:05 UTC, merged