🐛 Fix Compilation
Polimec/polimec-node pull request #364
Opened 2024-07-22 12:20 UTC by JuaniRios

## What?
- Make the repo compile for a release build and testing

## Why?
- Can't start fixing tests if it won't even compile

## How?
- Remove pallet-sandbox (was pretty old already and not in use)
- Remove old migration code and runtime item
- Add `FundingSuccessThreshold` (33%) to runtime
- Fix basecall filter

## Testing?
- `cargo build --release` and `cargo test` on root folder

## Anything Else?
- Benchmarks still not compiling, will take significant rewrite

2024-07-22 12:21 UTC, JuaniRios commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/364?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#364** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/364?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#363** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/363?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#362** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/362?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#361** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/361?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#358** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-02 11:59 UTC, vstam1 requested changes

2024-08-02 11:59 UTC, vstam1 commented on pallets/funding/src/functions/misc.rs
> -		// TODO: FIX event transmition by either doing it outside function or map ProjectStatus
Keep TODO until fixed?

2024-08-02 11:59 UTC, vstam1 commented on pallets/funding/src/storage_migrations.rs
> +//
Delete instead of commenting out?

2024-08-02 11:59 UTC, vstam1 commented on runtimes/polimec/src/lib.rs
> +	type FundingSuccessThreshold = ();
Might be good to actually properly set this value to 33%?

2024-08-02 11:59 UTC, vstam1 commented on runtimes/polimec/src/lib.rs
> -							pallet_funding::Call::root_do_community_funding { .. } |
Add the new runtime calls to the filter, so root -> non root call instead of only removing root?

2024-08-06 08:07 UTC, lrazovic approved these changes

2024-08-09 10:20 UTC, vstam1 approved these changes

2024-08-23 09:56 UTC, JuaniRios commented
### Merge activity

* **Aug 23, 5:56 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/364).

2024-08-23 10:08 UTC, merged