Runtime Upgrade
Polimec/polimec-node pull request #383
Opened 2024-08-27 10:49 UTC by JuaniRios

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-08-27 10:50 UTC, JuaniRios commented
* **#383** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/383?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 12:58 UTC, lrazovic requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xPvTQnLOCB6vOZ5uHdYW/6b9125e4-6ef8-419e-95c3-315248c4d1f4.png)

Let's resolve the warnings and then LGTM

2024-09-03 14:02 UTC, lrazovic requested changes

2024-09-03 14:02 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
>  	transaction_version: 4,
Last thing: we should also bump the transaction_version

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/xPvTQnLOCB6vOZ5uHdYW/598ab060-9ebf-415d-be47-bcde6993d008.png)

2024-09-03 14:12 UTC, lrazovic approved these changes

2024-09-03 14:13 UTC, JuaniRios commented
### Merge activity

* **Sep 3, 10:13 AM EDT**: @JuaniRios started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/383).

2024-09-03 14:34 UTC, merged