Use skip-feeless-payment pallet
Polimec/polimec-node pull request #411
Opened 2024-10-09 14:06 UTC by JuaniRios

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-10-09 14:07 UTC, JuaniRios commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/411?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#411** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/411?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#408** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/408?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#406** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/406?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#407](https://github.com/Polimec/polimec-node/pull/407) <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/407?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#405** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/405?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#404** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/404?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#403** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/403?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#402** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/402?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#401** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/401?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#399** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/399?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-10 13:28 UTC, lrazovic requested changes
LGTM modulo the TODO that we can now remove

2024-10-10 13:28 UTC, lrazovic commented on runtimes/polimec/src/lib.rs
> +	// pallet_dispenser::extensions::SkipCheckIfFeeless<Runtime, pallet_asset_tx_payment::ChargeAssetTxPayment<Runtime>>,
Please remove the TODO and the commented-out code

2024-10-10 13:40 UTC, lrazovic commented on pallets/dispenser/src/extensions.rs
> +use frame_support::{dispatch::DispatchInfo, pallet_prelude::*, traits::IsSubType};
We can also get rid of:

+ warning: unused import: `StaticTypeInfo`
+ warning: unused import: `PostDispatchInfoOf`

2024-10-10 13:52 UTC, lrazovic approved these changes

2024-10-10 14:33 UTC, merged