Ethereum compatibility
Polimec/polimec-node pull request #420
Opened 2024-10-14 14:04 UTC by JuaniRios

## What?

## Why?

## How?

## Testing?

## Screenshots (optional)

## Anything Else?

2024-10-14 14:04 UTC, JuaniRios commented
* **#420** <a href="https://app.graphite.dev/github/pr/Polimec/polimec-node/420?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JuaniRios and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-06 11:33 UTC, vstam1 approved these changes
Lgtm. Cannot verify signature verification, but logic looks solid

2024-11-07 10:23 UTC, Lederstrumpf approved these changes
### Act I.
> 🚬 [...] #420

Clown

### Act II.

![2024-11-07T11:11:40,474664775+01:00](https://github.com/user-attachments/assets/017b23a9-ea44-465d-93bd-367b268a2faa)

Superclown
### Act III.
> ### Testing?
> In the next PR

Gigaclown :D

---

LGTM :+1: - follows EIP-191 well. Just note my comments re. recid value in sigs. I'm aware `ethers` still uses "legacy" by default - it's a minor adjustment.

2024-11-28 11:54 UTC, JuaniRios commented on pallets/funding/src/functions/misc.rs
> +				}
Tried signing with Ethereum wallets using the newest signing standard EIP-712 (TypedDatav4) and it still uses the old recid

2025-01-14 10:32 UTC, lrazovic requested changes
The logic looks good! I proposed few improvements on the EIP-712 side, so we can get rid of the `Vec`. Also, we should add benchmarks for the new receiving account extrinsics since we're doing extra computation for the signature verification (ECDSA/sr25519) in there.

2025-01-14 10:32 UTC, lrazovic commented on pallets/funding/src/functions/misc.rs
> +		let encoded_domain_type =
The Hash of ""EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)" is stable, we can pre-compute it instead of computing it every time. It should look something like this

```rust
/// EIP-712 domain separator calculation
/// RFC: https://eips.ethereum.org/EIPS/eip-712
pub const DOMAIN_TYPE_HASH: &[u8; 32] = &[
    // keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)")
    0x8b, 0x73, 0xc3, 0xc6, 0x9b, 0xb8, 0xfe, 0x3d, 
    0x51, 0x2e, 0xcc, 0x4c, 0xf7, 0x59, 0xcc, 0x79, 
    0x23, 0x9f, 0x7b, 0x17, 0x9b, 0x0f, 0xfa, 0xdb, 
    0xa7, 0x2d, 0xef, 0x6c, 0x7c, 0x5d, 0x5c, 0x4c
];
```

2025-01-14 10:32 UTC, lrazovic commented on pallets/funding/src/functions/misc.rs
> +		let mut data = Vec::new();
Since the size of the final array is known, I would replace the `Vec` with fixed-size array. In this way we should also get rid of the `.unwrap()`. Also the `copy_from_slice` should not fails since the data is composed by components with a precise size of 32 bytes (keccak output). So the total size is fixed at 32 * 5 = 160 bytes.

A proposed solution could be:

```rust
    let mut data = [0u8; 32 * 5]; // Space for all 5 32-byte components
    
    // Copy pre-computed domain type hash
    data[..32].copy_from_slice(DOMAIN_TYPE_HASH);
    
    // Hash and copy name
    let name_hash = keccak_256(name.as_bytes());
    data[32..64].copy_from_slice(&name_hash);
    
    // Hash and copy version
    let version_hash = keccak_256(version.as_bytes());
    data[64..96].copy_from_slice(&version_hash);
    
    // Convert chain_id to big-endian bytes and pad left with zeros
    let chain_id_bytes = chain_id.to_be_bytes();
    data[124..128].copy_from_slice(&chain_id_bytes);
    
    // Decode and validate contract address
    let contract_bytes = hex::decode(verifying_contract)
        .map_err(|_| ERROR)?;
    
    if contract_bytes.len() != ADDRESS_LENGTH {
        return Err(ERROR);
    }
    
    // Copy contract address with proper padding
    data[140..160].copy_from_slice(&contract_bytes);
    
    // Calculate final hash
    keccak_256(&data)
```

2025-01-14 10:32 UTC, lrazovic commented on pallets/funding/src/functions/misc.rs
> +	pub fn get_message(polimec_account: &str, project_id: u32, nonce: u32) -> [u8; 32] {
Similar to before, we can precompute the hash and pre-allocate a fixed size array for all components

2025-01-14 10:32 UTC, lrazovic commented on pallets/funding/src/functions/misc.rs
> +	pub fn get_eip_712_message(polimec_account: &str, project_id: u32, nonce: u32) -> [u8; 32] {
Also here we can get rid of the `Vec`. The prefix is constant 

```
const EIP712_PREFIX: [u8; 2] = [0x19, 0x01];
const TOTAL_MESSAGE_LENGTH: usize = 2 + 32 + 32; // prefix + domain_separator + message
```

And, applying the same logic saw before

```
    // Pre-allocate fixed size array for all components
    let mut data = [0u8; TOTAL_MESSAGE_LENGTH];
    
    // Copy the EIP-712 prefix
    data[..2].copy_from_slice(&EIP712_PREFIX);
    
    // Get domain separator and copy it
    let domain_separator = get_domain_separator(
        "Polimec",
        "1",
        1,
        "0000000000000000000000000000000000003344"
    )?;
    data[2..34].copy_from_slice(&domain_separator);
    
    // Get message hash and copy it
    let message = get_message(polimec_account, project_id, nonce)?;
    data[34..66].copy_from_slice(&message);
    
    // Calculate final hash
   keccak_256(&data)
```

2025-01-16 12:07 UTC, lrazovic approved these changes

2025-01-16 12:09 UTC, JuaniRios commented
### Merge activity

* **Jan 16, 7:09 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Polimec/polimec-node/420).

2025-01-16 12:09 UTC, merged